version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp

## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired

  sniproxy:
    image: lancachenet/sniproxy:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 443:443/tcp

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - lancache/cache:/data/cache
      - lancache/logs:/data/logs

volumes:
  lancache:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=ds120j,nolock,soft,rw"
      device: ":/volume1/lancache"
